

services:
  backend:
    build: .
    container_name: pathfinder-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: pathfinder-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: pathfinder_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: